In [3]:
pip install numpy

     ---------------------------------------- 13.1/13.1 MB 4.2 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [7]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr2 = np.array([[1,2,3],[2,3,4],[3,4,5]])
arr2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [12]:
zeros_arr = np.zeros(5)
zeros_arr

array([0., 0., 0., 0., 0.])

In [14]:
zeros_arr = zeros_arr.astype(int)
zeros_arr

array([0, 0, 0, 0, 0])

In [16]:
zeros_arr = zeros_arr.astype(float)
zeros_arr

array([0., 0., 0., 0., 0.])

In [18]:
arr2d = np.array([[1,2,3],[2,3,4],[2,3,4],[3,4,5]])
arr2d

array([[1, 2, 3],
       [2, 3, 4],
       [2, 3, 4],
       [3, 4, 5]])

In [20]:
arr2d.shape

(4, 3)

In [21]:
arr2d.ndim

2

In [28]:
arr.dtype

dtype('int64')

In [39]:
np.swapaxes(arr2d,1,0)

array([[1, 2, 2, 3],
       [2, 3, 3, 4],
       [3, 4, 4, 5]])

In [44]:
arr2d.reshape(3,4)

array([[1, 2, 3, 2],
       [3, 4, 2, 3],
       [4, 3, 4, 5]])

In [61]:
np.linspace(5,15,5, dtype="int")

array([ 5,  7, 10, 12, 15])

In [52]:
arr2d.sort
arr2d

array([[1, 2, 3],
       [2, 3, 4],
       [2, 3, 4],
       [3, 4, 5]])

In [63]:
arr2d.sort(1)
arr2d

array([[1, 2, 3],
       [2, 3, 4],
       [2, 3, 4],
       [3, 4, 5]])